# Generated by Django 4.2.5 on 2023-10-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_cars_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.ImageField(upload_to='catalog/static/img', verbose_name='Фотография'),
        ),
    ]
