# Generated by Django 4.2.5 on 2023-10-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_cars_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='img',
            field=models.ImageField(upload_to='static/img', verbose_name='Фотография'),
        ),
    ]
