# Generated by Django 4.2.5 on 2023-10-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_cars_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='body_type',
            field=models.IntegerField(choices=[(1, 'Универсал'), (2, 'Седан'), (3, 'Хэтчбек'), (4, 'Кабриолет'), (5, 'Внедорожник'), (6, 'Кроссовер'), (7, 'Купе'), (8, 'Лифтбек'), (9, 'Пикак'), (10, 'Минивен'), (11, 'Лифтбек')], default=0, verbose_name='Тип кузова'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='drive_type',
            field=models.IntegerField(choices=[(1, 'Передний'), (2, 'Задний'), (3, 'Полный')], default=1, verbose_name='Привод'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.FloatField(default=1, verbose_name='Объем двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel',
            field=models.IntegerField(choices=[(1, 'Дизель'), (2, 'Бензин')], default=1, verbose_name='Тип топлива'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='gear',
            field=models.IntegerField(choices=[(1, 'Механическая'), (2, 'Автомат')], default=1, verbose_name='Коробка передач'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(default=1, verbose_name='Пробег'),
            preserve_default=False,
        ),
    ]
