# Generated by Django 4.2.5 on 2023-10-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_cars_body_type_cars_drive_type_cars_engine_cars_fuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(default=1, max_length=15, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='fuel',
            field=models.IntegerField(choices=[(1, 'Дизель'), (2, 'Бензин')], default=1, verbose_name='Тип топлива'),
        ),
    ]
