# Generated by Django 4.2.5 on 2023-10-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_cars_color_alter_cars_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='body_type',
            field=models.CharField(choices=[('Универсал', 'Универсал'), ('Седан', 'Седан'), ('Хэтчбек', 'Хэтчбек'), ('Кабриолет', 'Кабриолет'), ('Внедорожник', 'Внедорожник'), ('Кроссовер', 'Кроссовер'), ('Купе', 'Купе'), ('Лифтбек', 'Лифтбек'), ('Пикап', 'Пикап'), ('Минивен', 'Минивен'), ('Лифтбек', 'Лифтбек')], default='Седан', max_length=20, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='drive_type',
            field=models.CharField(choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('Полный', 'Полный')], default='Задний', max_length=20, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='fuel',
            field=models.IntegerField(choices=[(1, 'Дизель'), (2, 'Бензин')], default='Бензин', max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='gear',
            field=models.CharField(choices=[('Механическая', 'Механическая'), ('Автомат', 'Автомат')], default='Автомат', max_length=20, verbose_name='Коробка передач'),
        ),
    ]
