# Generated by Django 4.2.5 on 2023-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_cars_body_type_alter_cars_drive_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='fuel',
            field=models.CharField(choices=[('Дизель', 'Дизель'), ('Бензин', 'Бензин')], default='Бензин', max_length=20, verbose_name='Тип топлива'),
        ),
    ]
