# Generated by Django 4.2.5 on 2023-10-24 22:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_rename_customuser_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='CustomUser',
        ),
    ]
