# Generated by Django 4.2.5 on 2023-10-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_profile_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='user/static/user/img/profile.png', upload_to='user/static/user/img', verbose_name='Аватар'),
        ),
    ]
