# Generated by Django 4.2.5 on 2023-10-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='static/avatars/profile.png', upload_to='static/avatars', verbose_name='Аватар'),
        ),
    ]
