# Generated by Django 4.2.5 on 2023-10-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Имя', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(default='Фамилия', max_length=30),
        ),
    ]
